[versions]
kotlin = "1.8.0"
compose = "1.3.0"
aurora = "1.4-SNAPSHOT"
radiance = "7.0-SNAPSHOT"
versionchecker = "0.44.0"

[libraries]
compose-desktop = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

aurora-theming = { module = "org.pushing-pixels:aurora-theming", version.ref = "aurora" }
aurora-component = { module = "org.pushing-pixels:aurora-component", version.ref = "aurora" }
aurora-window = { module = "org.pushing-pixels:aurora-window", version.ref = "aurora" }
aurora-svgtranscoder-gradlePlugin = { module = "org.pushing-pixels:aurora-tools-svg-transcoder-gradle-plugin", version.ref = "aurora" }

radiance-theming = { module = "org.pushing-pixels:radiance-theming", version.ref = "radiance" }

versionchecker-gradlePlugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionchecker" }
